version: '3.8'

services:
    prod:
        build:
            context: .
            dockerfile: ./Dockerfile.prod
        command: npm run start:prod
        ports:
            - 8080:3000
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped

networks:
    nesjs-network: