version: '3'
services:
    prod:
        build:
            context: .
            dockerfile: ./Dockerfile.prod
        command: npm run start:dev
        ports:
            - 8080:8080
        networks:
            - nestjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped

networks:
    nestjs-network:

